//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloppyFinchWindows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FloppyFinchWindows.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AccountActionConfirmationMessageBox {
            get {
                return ResourceManager.GetString("AccountActionConfirmationMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account&apos;s data successfully cleared..
        /// </summary>
        public static string AccountDataClearedMessageBox {
            get {
                return ResourceManager.GetString("AccountDataClearedMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully..
        /// </summary>
        public static string AccountDeletedSuccessMessageBox {
            get {
                return ResourceManager.GetString("AccountDeletedSuccessMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string AccountSettingsLabelText {
            get {
                return ResourceManager.GetString("AccountSettingsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string AppearanceDarkModeComboBoxItemText {
            get {
                return ResourceManager.GetString("AppearanceDarkModeComboBoxItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string AppearanceLightModeComboBoxItemText {
            get {
                return ResourceManager.GetString("AppearanceLightModeComboBoxItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird Skins.
        /// </summary>
        public static string BirdSkinsShopHeader {
            get {
                return ResourceManager.GetString("BirdSkinsShopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string BlackSkinLabelText {
            get {
                return ResourceManager.GetString("BlackSkinLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string BlueSkinLabelText {
            get {
                return ResourceManager.GetString("BlueSkinLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose background appearance:.
        /// </summary>
        public static string ChoseAppearanceLabelText {
            get {
                return ResourceManager.GetString("ChoseAppearanceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose language:.
        /// </summary>
        public static string ChoseLanguageLabelText {
            get {
                return ResourceManager.GetString("ChoseLanguageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose resolution preset:.
        /// </summary>
        public static string ChoseResolutionLabelText {
            get {
                return ResourceManager.GetString("ChoseResolutionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string ClassicSkinLabelText {
            get {
                return ResourceManager.GetString("ClassicSkinLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear account data.
        /// </summary>
        public static string ClearAccountDataButtonText {
            get {
                return ResourceManager.GetString("ClearAccountDataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear account data..
        /// </summary>
        public static string ClearAccountDataTitleMessageBox {
            get {
                return ResourceManager.GetString("ClearAccountDataTitleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string CongratulationsLabelContent {
            get {
                return ResourceManager.GetString("CongratulationsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccountButtonText {
            get {
                return ResourceManager.GetString("DeleteAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account..
        /// </summary>
        public static string DeleteAccountTitleMessageBox {
            get {
                return ResourceManager.GetString("DeleteAccountTitleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speed = 7; Default speed = 5..
        /// </summary>
        public static string FasterSpeedToolTipText {
            get {
                return ResourceManager.GetString("FasterSpeedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speed = 10; Default speed = 5..
        /// </summary>
        public static string FastSpeedToolTipText {
            get {
                return ResourceManager.GetString("FastSpeedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Place.
        /// </summary>
        public static string FirstPlaceTextBlockText {
            get {
                return ResourceManager.GetString("FirstPlaceTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over.
        /// </summary>
        public static string GameOverLabelContent {
            get {
                return ResourceManager.GetString("GameOverLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay Settings.
        /// </summary>
        public static string GameplaySettingsLabelText {
            get {
                return ResourceManager.GetString("GameplaySettingsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string GreenSkinLabelText {
            get {
                return ResourceManager.GetString("GreenSkinLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetpack.
        /// </summary>
        public static string JetpackPowerUpLabelText {
            get {
                return ResourceManager.GetString("JetpackPowerUpLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LeaderboardButtonText {
            get {
                return ResourceManager.GetString("LeaderboardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string MainMenuButtonText {
            get {
                return ResourceManager.GetString("MainMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New high score:.
        /// </summary>
        public static string NewHighScoreTextBoxText {
            get {
                return ResourceManager.GetString("NewHighScoreTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough coins..
        /// </summary>
        public static string NotEnoughCoinsText {
            get {
                return ResourceManager.GetString("NotEnoughCoinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseButtonText {
            get {
                return ResourceManager.GetString("PauseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string PinkSkinLabelText {
            get {
                return ResourceManager.GetString("PinkSkinLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayButtonText {
            get {
                return ResourceManager.GetString("PlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic mode.
        /// </summary>
        public static string PlayClassicModeText {
            get {
                return ResourceManager.GetString("PlayClassicModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended mode.
        /// </summary>
        public static string PlayExtendedModeText {
            get {
                return ResourceManager.GetString("PlayExtendedModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed race.
        /// </summary>
        public static string PlaySpeedRaceModeText {
            get {
                return ResourceManager.GetString("PlaySpeedRaceModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target score.
        /// </summary>
        public static string PlayTargetScoreModeText {
            get {
                return ResourceManager.GetString("PlayTargetScoreModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string PowerUpLevelTextBoxText {
            get {
                return ResourceManager.GetString("PowerUpLevelTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-ups.
        /// </summary>
        public static string PowerUpsShopHeader {
            get {
                return ResourceManager.GetString("PowerUpsShopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press space to start.
        /// </summary>
        public static string PressSpaceTextBlockText {
            get {
                return ResourceManager.GetString("PressSpaceTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset screen position.
        /// </summary>
        public static string ResetScreenPositionButtonText {
            get {
                return ResourceManager.GetString("ResetScreenPositionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To adjust resolution resize window..
        /// </summary>
        public static string ResizeWindowToolTipText {
            get {
                return ResourceManager.GetString("ResizeWindowToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartButtonText {
            get {
                return ResourceManager.GetString("RestartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ResumeButtonText {
            get {
                return ResourceManager.GetString("ResumeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Multiplier.
        /// </summary>
        public static string ScoreMultiplierPowerUpLabelText {
            get {
                return ResourceManager.GetString("ScoreMultiplierPowerUpLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set own speed:.
        /// </summary>
        public static string SetOwnSpeedLabelContent {
            get {
                return ResourceManager.GetString("SetOwnSpeedLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string ShieldPowerUpLabelText {
            get {
                return ResourceManager.GetString("ShieldPowerUpLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ShopButtonText {
            get {
                return ResourceManager.GetString("ShopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutButtonText {
            get {
                return ResourceManager.GetString("SignOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speed = 3; Default speed = 5..
        /// </summary>
        public static string SlowSpeedToolTipText {
            get {
                return ResourceManager.GetString("SlowSpeedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string SpeedFastButtonText {
            get {
                return ResourceManager.GetString("SpeedFastButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster.
        /// </summary>
        public static string SpeedFasterButtonText {
            get {
                return ResourceManager.GetString("SpeedFasterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed presets:.
        /// </summary>
        public static string SpeedPresetLabelContent {
            get {
                return ResourceManager.GetString("SpeedPresetLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string SpeedSlowButtonText {
            get {
                return ResourceManager.GetString("SpeedSlowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum speed = 1, maximum speed = 13..
        /// </summary>
        public static string SpeedToolTipText {
            get {
                return ResourceManager.GetString("SpeedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string SuccessTitleMessageBox {
            get {
                return ResourceManager.GetString("SuccessTitleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target score: .
        /// </summary>
        public static string TargetScoreTextBlockText {
            get {
                return ResourceManager.GetString("TargetScoreTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string WhiteSkinLabelText {
            get {
                return ResourceManager.GetString("WhiteSkinLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scored:.
        /// </summary>
        public static string YouScoredTextBlockText {
            get {
                return ResourceManager.GetString("YouScoredTextBlockText", resourceCulture);
            }
        }
    }
}
